server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/user-service
          predicates:
            - Path=/user-service/**
        - id: parking-service
          uri: http://localhost:8082/parking-service
          predicates:
            - Path=/parking-service/**
        - id: vehicle-service
          uri: http://localhost:8083/vehicle-service
          predicates:
            - Path=/vehicle-service/**
        - id: payment-service
          uri: http://localhost:8084/payment-service
          predicates:
            - Path=/payment-service/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
